### ISSUE TITLE
How to use and visualize?

### ISSUE THREAD

**Issue by xlong0513** [sanjayankur31/bionav#1]
Hi, @sanjayankur31, Thanks for the code. Can the system be used right now? And how to run it?

**Comment by sanjayankur31** [comment]
hi @xlong0513 : I'm not sure, I haven't used this in ~6 years now, so I'm not even sure if it still functions on the newer ROS releases.

It used to be run like a standard ROS node: you need to set up the rest of your ROS environment and then run this like any other subscriber/producer. Another subscriber would be used to collect the data and then it was plotted offline.
